theme: minima
title: Journey to Programming
author: John Carreos
email: jrcarreos1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog for documenting my progress in learning to program. I still need to learn a lot in writing and programming. 
  Please send me your comments and suggestions. I'd love to hear it.

# social links
github_username:  JohnCarreos # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
